name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Compilar APK con Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: buildozer android debug
          buildozer_version: stable

      - name: Subir el APK generado
        uses: actions/upload-artifact@v4
        with:
          name: transcripciones-youtube-apk
          path: bin/*.apk
